#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     HTMUX1,         sensorI2CCustom)
#pragma config(Sensor, S3,     elevatorLimitSW, sensorTouch)
#pragma config(Sensor, S4,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rearLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rearRightMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     brushMotor,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     elevatorMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    goalCaptureServo,     tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    drawBridgeServo,      tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    goalGrabberServo,     tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define leftIR                  msensor_S2_3
#define rightIR                 msensor_S2_4
//#define frontSonar              msensor_S2_2
//#define backSonar               msensor_S2_1

#if 0
/// Copyright (c) Titan Robotics Club. All rights reserved.
///
/// <module name="TeleOp.c" />
///
/// <summary>
///     This module is a template file and should not be modified except for
///     the above motor and sensor definitions. Code common to both Autonmous
///     and TeleOp modes should live in CommonCode.h. Code specific to only
///     TeleOp mode should live in TeleOpCode.h.
/// </summary>
///
/// <remarks>
///     Environment: RobotC for Lego Mindstorms NXT.
/// </remarks>
#endif

#include "JoystickDriver.c"
#include "..\ftclib\trcdefs.h"
#include "..\ftclib\dbgtrace.h"

#define _TELEOP_ONLY
#define _TEAM_3543

#include "..\CascadeEffect\CommonCode.h"
#include "..\CascadeEffect\TeleOpCode.h"

/**
 *  This function is called to initialize the robot. It does initializations
 *  common to both Autonomous and TeleOp modes as well as initializations
 *  specific only to TeleOp mode.
 */
void RobotInit()
{
    CommonInit();
    TeleOpInit();
}   //RobotInit

/**
 *  This function is called before TeleOp mode starts.
 *
 *  @param pgmMode Specifies the program mode (TeleOp in this case).
 */
void StartMode(int pgmMode)
{
    TeleOpStart();
}   //StartMode

/**
 *  This function is called after TeleOp mode ends.
 *
 *  @param pgmMode Specifies the program mode (TeleOp in this case).
 */
void StopMode(int pgmMode)
{
    TeleOpStop();
}   //StopMode

/**
 *  This function is called to perform high frequency tasks that are common to
 *  both Autonomous and TeleOp modes as well as specific only to TeleOp mode.
 *
 *  @param pgmMode Specifies the program mode (TeleOp in this case).
 */
void HiFreqTasks(int pgmMode)
{
    CommonHiFreqTasks();
    TeleOpHiFreqTasks();
}   //HiFreqTasks

/**
 *  This function is called to perform input tasks that are common to both
 *  Autonomous and TeleOp modes as well as specific only to TeleOp mode.
 *
 *  @param pgmMode Specifies the program mode (TeleOp in this case).
 */
void InputTasks(int pgmMode)
{
    CommonInputTasks();
    TeleOpInputTasks();
}   //InputTasks

/**
 *  This function is called to perform the main competition tasks.
 *
 *  @param pgmMode Specifies the program mode (TeleOp in this case).
 *  @param time Specifies the running time since the mode started.
 */
void MainTasks(int pgmMode, float time)
{
    TeleOpTasks(time);
}   //MainTasks

/**
 *  This function is called to perform output tasks that are common to both
 *  Autonomous and TeleOp modes as well as specific only to TeleOp mode.
 *
 *  @param pgmMode Specifies the program mode (TeleOp in this case).
 */
void OutputTasks(int pgmMode)
{
    TeleOpOutputTasks();
    CommonOutputTasks();
}   //OutputTasks

#include "..\ftclib\FtcTeleOp.h"
