#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "..\ftclib\trcdefs.h"
#include "..\ftclib\dbgtrace.h"
#include "..\ftclib\batt.h"
#include "..\ftclib\menu.h"

#define POS_INC                 1

BATT    g_batt;
MENU    g_testMenu;
int     g_testChoice;

void DoEncoderTest(tMotor motorID)
{
    nxtDisplayTextLine(0, "Encoder Test:");
    nMotorEncoder[motorID] = 0;
    while (true)
    {
        motor[motorID] = 30;
        nxtDisplayCenteredBigTextLine(2, "%d", nMotorEncoder[motorID]);
        BattTask(g_batt);
        wait1Msec(100);
    }
}   //DoEncoderTest

void DoMotorTest(tMotor motorID)
{
}   //DoMotorTest

void DoServoTest(TServoIndex servoID)
{
    int pos = 0;

    nxtDisplayTextLine(0, "180 Servo Test:");
    servo[servoID] = 0;
    wait1Msec(1000);

    while (true)
    {
        nxtDisplayCenteredBigTextLine(2, "%d", pos);
        servo[servoID] = pos;
        if (nNxtButtonPressed == kLeftButton)
        {
            pos -= POS_INC;
            if (pos < 0)
            {
                pos = 0;
            }
        }
        else if (nNxtButtonPressed == kRightButton)
        {
            pos += POS_INC;
            if (pos > 255)
            {
                pos = 255;
            }
        }
        BattTask(g_batt);
        wait1Msec(100);
    }
}

task main()
{
    BattInit(g_batt, 5, true);
    MenuInit(g_testMenu, "Tests:");
    MenuAddChoice(g_testMenu, "Encoder", 0);
    MenuAddChoice(g_testMenu, "Motor1", 1);
    MenuAddChoice(g_testMenu, "Motor2", 2);
    MenuAddChoice(g_testMenu, "180-Servo", 3);
    g_testChoice = MenuGetChoice(g_testMenu);

    switch (g_testChoice)
    {
        case 0:
            DoEncoderTest(motor1);
            break;
        case 1:
            DoMotorTest(motor1);
            break;
        case 2:
            DoMotorTest(motor2);
            break;
        case 3:
            DoServoTest(servo1);
            break;
        default:
            break;
    }
}   //main
